arreglar build4

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,14 +67,14 @@ jobs:
                 --url "https://florgalarza.atlassian.net/rest/api/3/issue/$ISSUE_KEY/transitions" \
                 --user "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
                 --header "Content-Type: application/json" \
-                --data '{"transition": {"id": "21"}}'
+                --data '{"transition": {"id": "21"}}' || echo "Error al mover $ISSUE_KEY a En curso. Continuando con la build..."
             elif [ "$GITHUB_REF" == "refs/heads/main" ]; then
               echo "Moviendo $ISSUE_KEY a Finalizada (Done)..."
               curl --request POST \
                 --url "https://florgalarza.atlassian.net/rest/api/3/issue/$ISSUE_KEY/transitions" \
                 --user "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
                 --header "Content-Type: application/json" \
-                --data '{"transition": {"id": "31"}}'
+                --data '{"transition": {"id": "31"}}' || echo "Error al mover $ISSUE_KEY a Finalizada. Continuando con la build..."
             else
               echo "No se detectó acción válida para Jira."
             fi
@@ -90,7 +90,7 @@ jobs:
               --url "https://florgalarza.atlassian.net/rest/api/3/issue/$ISSUE_KEY/transitions" \
               --user "${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
               --header "Content-Type: application/json" \
-              --data '{"transition": {"id": "31"}}'
+              --data '{"transition": {"id": "31"}}' || echo "Error al mover $ISSUE_KEY a Finalizada. Continuando con la build..."
           else
             echo "No se encontró un ISSUE_KEY en el mensaje del commit. Continuando con la build..."
           fi
